pipeline {
    agent any
    stages {
        stage('Clonar repositorio') {
            steps {
                git url: 'URL_DE_TU_REPOSITORIO.git', branch: 'main'
            }
        }
        stage('Instalar dependencias') {
            steps {
                sh 'pip install -r requirements.txt'
            }
        }
        stage('Ejecutar pruebas') {
            steps {
                sh 'mkdir -p reports'  // Crear carpeta para los reportes
                sh 'behave --no-capture features/SavingsAndInvestments.feature --format pretty --format junit --out reports --format html --out reports/report.html'
            }
        }
    }
    post {
        always {
            junit 'reports/*.xml'
            publishHTML(
                target: [
                    allowMissing: false,
                    alwaysLinkToLastBuild: true,
                    keepAll: true,
                    reportDir: 'reports',
                    reportFiles: 'report.html',
                    reportName: 'Reporte de Pruebas'
                ]
            )
        }
    }
}
